version: '2.2'
  
services:
  mongonarcis:
    command: mongod --setParameter failIndexKeyTooLong=false
    container_name: mongo
    image: mongo:4.0
    ports:
      - "27101:27017" # map port to none standard port, to avoid conflicts with locally installed mongodb. 
    volumes:
      - mongodata0:/data/db
      - ./data/original:/exchange

  es0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es0-doiboost
    ports:
      - "9201:9200"
    environment:
      - node.name=es0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2024m -Xms2024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - esdata0:/usr/share/elasticsearch/data
      - ./data/original:/exchange

  jupyter:
    build: ./notebooks
    ports:
      - "8880:8888"
    volumes:
      - ./data/original:/exchange
      - ./notebooks/persistent/:/home/

  web:
    build: ./narcisweb
    restart: always
    ports:
      - "8085:5000"
    environment:
      - "DOCKER_MACHINE_IP=0.0.0.0"
    volumes:
      - ./data/original:/exchange
    depends_on:
      - mongonarcis
      - es0

volumes:
  esdata0:
    driver: local
  mongodata0:
    driver: local
